#this simple webserver only displays one page called page.html, that 
#is generated by the book_cover.py program.   it also only displace three different
#images:   image.jpg, rectangle.jpg and rectangle-capure.jpg
#it has no security and runs on port 8888.   so use with care.

import tornado.ioloop
import tornado.web

class MainHandler(tornado.web.RequestHandler):
    def check_origin(self, origin):
        return True
    def get(self):
        f = open("page.html", "rb")
        txt = f.read()
        self.write(txt)


class ImageHandler(tornado.web.RequestHandler):
    def get(self):
        imgf = open("image.jpg", "rb")
        img = imgf.read()
        self.set_header('Content-Type', 'image/jpg')
        self.write(img)

class ImageHandler2(tornado.web.RequestHandler):
    def get(self):
        imgf = open("rectangle.jpg", "rb")
        img = imgf.read()
        self.set_header('Content-Type', 'image/jpg')
        self.write(img)

class ImageHandler3(tornado.web.RequestHandler):
    def get(self):
        imgf = open("rectangle-capure.jpg", "rb")
        img = imgf.read()
        self.set_header('Content-Type', 'image/jpg')
        self.write(img)


def make_app():
    return tornado.web.Application([
        (r"/", MainHandler),
        (r"/image.jpg", ImageHandler),
        (r"/rectangle.jpg", ImageHandler2),
        (r"/rectangle-capture.jpg", ImageHandler3),
    ])

if __name__ == "__main__":
    app = make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()
